healthCheckCms:
  handler: src/adapters/driving-adapters/lambda/healthCheckHandler.handler
  description: Check the health of the gateway
  events:
    - http:
        path: indexing-prompts/health-check
        method: GET
        cors: true
