- Effect: Allow
  Action:
    - dynamodb:Scan
    - dynamodb:Query
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  Resource:
    - arn:aws:dynamodb:*:*:table/indexing-${sls:stage}-prompt-table
    - arn:aws:dynamodb:*:*:table/indexing-${sls:stage}-prompt-table/index/*
